using System.Diagnostics.CodeAnalysis;

namespace Game.Catalogs;

[SuppressMessage("ReSharper", "InconsistentNaming")]
internal enum InteractionHandlerId : ushort
{
    None = 0x0000,

    // Shared
    Shared_ToggleSelectionDataState = 0x1B3F,

    // Inventory
    Inventory_BuyLiquidWhippedCream = 0x3BD3,
    Inventory_BuyRecycledWritingPaper = 0x3BAB,
    IngesShop_BuySprayCream = 0x37B4,
    IngesShop_BuyWhiteWritingPaper = 0x37F5,
    Inventory_InspectBallpointPen = 0x375C,
    Inventory_InspectBrochure = 0x388E,
    Inventory_InspectCarKey = 0x3B0C,
    Inventory_InspectLighter = 0x3C45,
    Inventory_InspectLiquidWhippedCream = 0x3796,
    Inventory_InspectNote = 0x1BBE,
    Inventory_InspectPhoneBook = 0x3A41,
    Inventory_InspectRecycledWritingPaper = 0x37C8,
    Inventory_InspectSprayCream = 0x37A5,
    Inventory_InspectStamp = 0x37D7,
    Inventory_InspectWallet = 0x2DFC,
    Inventory_InspectWhiteWritingPaper = 0x37E6,
    Inventory_ReadBrochure = 0x389D,
    Inventory_ReadPhoneBook = 0x3A50,
    Inventory_TakeBrochure = 0x38AC,
    Inventory_UseBallpointPenWithWritingPaper = 0x3BE5,
    Inventory_UseCreamWithBowl = 0x3C0B,
    Inventory_UseStampWithLetter = 0x3BF7,
    Inventory_UseWhiskWithBowl = 0x3C1F,

    // IngesShop
    IngesShop_BuyFireExtinguisher = 0x3BB8,
    IngesShop_BuyHalonifaxFireExtinguisher = 0x387A,
    IngesShop_InspectBell = 0x3818,
    IngesShop_InspectCashRegister = 0x3778,
    IngesShop_InspectCo2FireExtinguisher = 0x384D,
    IngesShop_InspectFireExtinguisher = 0x385C,
    IngesShop_InspectHalonifaxFireExtinguisher = 0x386B,
    IngesShop_InspectShelf = 0x3809,
    IngesShop_LaterDismissal = 0x383E,
    IngesShop_TakeCashRegister = 0x3787,
    IngesShop_UseBell = 0x3827,

    // City
    City_InspectWashingMachine = 0x38B9,
    City_UseBusStop = 0x20AA,
    City_UseQuickLaundromatDoor = 0x3DEC,
    City_UseWashingMachine = 0x38C8,

    // City2
    City2_InspectBillysBurgerBarDoor = 0x35C5,
    City2_InspectCigarette = 0x3617,
    City2_InspectIntBurgerConnectDoor = 0x358C,
    City2_InspectMailbox = 0x3529,
    City2_InspectSign = 0x35F9,
    City2_InspectTrash = 0x357D,
    City2_ReadSign = 0x3608,
    City2_UseLetterOnMailSlot = 0x3538,
    City2_VisitBillysBurgerBar = 0x35DC,
    City2_VisitIntBurgerConnect = 0x35A3,

    // House
    House_BusStopNoOp = 0x1BAA,
    House_InspectBicycle = 0x1C61,
    House_InspectBicyclePump = 0x22F6,
    House_InspectBusStop = 0x1E3D,
    House_InspectFriendlyMan = 0x3D04,
    House_InspectGarage = 0x1C26,
    House_InspectHouse = 0x1BCD,
    House_OpenBicycleLock = 0x26C0,
    House_OpenGarage = 0x2745,
    House_TakeBicyclePump = 0x2305,
    House_UseBicycle = 0x1CB4,
    House_UseBicyclePumpOnBicycle = 0x2312,
    House_UseBusStop = 0x1E59,
    House_UseGarage = 0x1C43,

    // LivingRoom
    LivingRoom_InspectAquarium = 0x2763,
    LivingRoom_InspectArmchair = 0x28FE,
    LivingRoom_InspectCrack = 0x28C4,
    LivingRoom_InspectLeftDrawer = 0x27C7,
    LivingRoom_InspectPhoto = 0x2781,
    LivingRoom_InspectPicture = 0x2754,
    LivingRoom_InspectRightDrawer = 0x281A,
    LivingRoom_InspectSwitch = 0x2844,
    LivingRoom_InspectTable = 0x28D3,
    LivingRoom_InspectWindow = 0x291A,
    LivingRoom_OpenCloseSwitch = 0x1BA5,
    LivingRoom_ReadPhoto = 0x2772,
    LivingRoom_SitOnArmchair = 0x28EF,
    LivingRoom_TakeLeftDrawerContents = 0x2790,
    LivingRoom_TakeRightDrawerContents = 0x27FE,
    LivingRoom_UseCrack = 0x28B5,
    LivingRoom_UseSwitch = 0x2853,

    // Garden
    Garden_InspectCompost = 0x2A8B,
    Garden_InspectFence = 0x2ABC,
    Garden_InspectLeafPile = 0x2978,
    Garden_InspectLounger = 0x2987,
    Garden_InspectStrawberry = 0x2AAD,
    Garden_InspectTree = 0x2ACB,
    Garden_TakeStrawberries = 0x2A9A,
    Garden_UseLeafPileOnCompost = 0x2929,
    Garden_UseLighterOnCompost = 0x3C54,
    Garden_UseLounger = 0x2996,

    // Basement
    Basement_InspectElectricHeater = 0x2B86,
    Basement_InspectFireExtinguisher = 0x2BA4,
    Basement_InspectHeatingSystem = 0x2BC0,
    Basement_InspectOutlet = 0x2BDC,
    Basement_UseElectricHeaterOnOutlet = 0x2ADA,
    Basement_UseFireExtinguisher = 0x2B95,

    // Kitchen
    Kitchen_InspectDishwasher = 0x2D57,
    Kitchen_InspectFaucet = 0x2C25,
    Kitchen_InspectOven = 0x2C50,
    Kitchen_InspectPlate = 0x2C07,
    Kitchen_InspectRefrigerator = 0x2CFA,
    Kitchen_InspectSink = 0x2D33,
    Kitchen_InspectWhisk = 0x2BEB,
    Kitchen_OpenRefrigerator = 0x2D24,
    Kitchen_TakeBowlFromOven = 0x2C7A,
    Kitchen_TakePlate = 0x2C16,
    Kitchen_TakeWhisk = 0x2BFA,
    Kitchen_ToggleOvenOpenState = 0x2CA4,
    Kitchen_UseDishwasher = 0x2D66,
    Kitchen_UseFaucet = 0x2C41,
    Kitchen_UseOven = 0x2C95,
    Kitchen_WashPlate = 0x2D42,

    // Bedroom
    Bedroom_ExitDoor = 0x3D45,
    Bedroom_InspectBed = 0x2DA7,
    Bedroom_InspectBird = 0x2DC3,
    Bedroom_InspectBox = 0x2DDF,
    Bedroom_InspectComputer = 0x2EA9,
    Bedroom_InspectHeater = 0x2EB8,
    Bedroom_InspectKeyboard = 0x2E82,
    Bedroom_InspectPinboard = 0x2D89,
    Bedroom_InspectPoster = 0x2D7A,
    Bedroom_OpenCloseBox = 0x2E2C,
    Bedroom_OpenWindow = 0x2F89,
    Bedroom_ReadPinboard = 0x2D98,
    Bedroom_TakeBoxContents = 0x2E0B,
    Bedroom_UseBtxTerminal = 0x2E9E,
    Bedroom_UseChair = 0x3524,
    Bedroom_UseComputer = 0x32D1,
    Bedroom_UseHeater = 0x2ED5,
    Bedroom_UseTelephone = 0x2FB1,

    // FurnitureStore
    FurnitureStore_BuyBed = 0x3676,
    FurnitureStore_BuyChristophColumbusArmchair = 0x3B51,
    FurnitureStore_BuyGlassTable = 0x3B6C,
    FurnitureStore_BuyOakenBed = 0x3B1B,
    FurnitureStore_BuyRefrigerator = 0x3B36,
    FurnitureStore_BuyRemoteControlledFridge = 0x36E9,
    FurnitureStore_BuySchaumiArmchair = 0x36A8,
    FurnitureStore_BuyTropicanaMattress = 0x3662,
    FurnitureStore_BuyWoodenTable = 0x3748,
    FurnitureStore_InspectChristophColumbusArmchair = 0x368A,
    FurnitureStore_InspectFedermatMattress = 0x3644,
    FurnitureStore_InspectGlassTable = 0x372A,
    FurnitureStore_InspectOakBed = 0x3626,
    FurnitureStore_InspectRemoteControlledFridge = 0x36DA,
    FurnitureStore_InspectRightFridge = 0x36CB,
    FurnitureStore_InspectSalesman = 0x370C,
    FurnitureStore_InspectSchaumiArmchair = 0x3699,
    FurnitureStore_InspectTropicanaBed = 0x3635,
    FurnitureStore_InspectTropicanaMattress = 0x3653,
    FurnitureStore_InspectWoodenTable = 0x3739,
    FurnitureStore_OpenFridge = 0x36FD,
    FurnitureStore_SitOnChristophColumbusArmchair = 0x36BC,
    FurnitureStore_TakeBallpointPen = 0x376B,
    FurnitureStore_UseSalesman = 0x371B
}
