using Game.Shared.Input;

namespace Game.Desktop.MonoGame;

/// <summary>
///     Captured keyboard state for one input poll.
/// </summary>
/// <param name="PressedKeys">Keys that are currently pressed.</param>
/// <param name="QueuedKeyStrokes">The queued keystrokes generated by this poll.</param>
internal readonly record struct KeyboardCaptureFrame(InputKey[] PressedKeys, InputKeyStroke[] QueuedKeyStrokes)
{
    /// <summary>
    ///     Empty keyboard capture frame.
    /// </summary>
    public static KeyboardCaptureFrame Empty { get; } = new([], []);
}
